name: Build Project with Prebuilt Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull Docker image
      run: docker pull sejokim/qt_cross:latest

    - name: Check files in project directory
      run: |
        docker run --rm --platform linux/arm64 -v ${{ github.workspace }}:/project -w /project sejokim/qt_cross:latest /bin/bash -c "
          echo 'Contents of /project before copy:' && \
          ls -la /project
        "

    - name: Build project inside Docker container
      run: |
        docker run --rm --platform linux/arm64 -v ${{ github.workspace }}:/project -w /project sejokim/qt_cross:latest /bin/bash -c "
          mkdir -p build && \
          find /project -mindepth 1 -maxdepth 1 ! -name build -exec cp -r {} build/ \; && \
          echo 'Contents of /project/build after copy:' && \
          ls -la /project/build && \
          cd build && \
          cmake . && \
          make && \
          cp InstrumentCluster /project/
        "

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: InstrumentCluster