name: CI Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker using official script
      run: |
        sudo apt-get update
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: Run build in Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace debian:bookworm-slim bash -c "
        apt-get update &&
        apt-get install -y build-essential qt6-base-dev qt6-tools-dev qt6-tools-dev-tools can-utils cmake python3 python3-pip python3.11-venv &&
        pip3 install -r requirements.txt &&
        mkdir -p build &&
        cd build &&
        cmake ../src &&
        make &&
        if [ -f ./PiRacerInstrumentCluster ]; then
          ./PiRacerInstrumentCluster --test
        else
          echo 'No test suite found'
          exit 1
        fi
        "

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/PiRacerInstrumentCluster
