name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t rpi-cross-compiler .

    - name: Run Cross-Compilation
      run: |
        docker run --rm -v $(pwd):/workspace rpi-cross-compiler

    - name: Upload Artifacts to Google Cloud Storage
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gsutil cp /workspace/build/my_project gs://${{ secrets.GCS_BUCKET }}/my_project