name: Cross-Compile and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull pre-built Docker image
      run: docker pull stateoftheartio/qt6:6.6-gcc-aqt

    - name: Run cross-compilation
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace stateoftheartio/qt6:6.6-gcc-aqt /bin/bash -c "
        cd /workspace/src && \
        sudo apt update && sudo apt install -y libgl-dev libvulkan-dev && \
        qt-cmake . -G Ninja -B build && \
        cmake --build build --parallel 8"
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: qt-cross-compiled
        path: /workspace/src/build